#############################################################################
# Makefile for building: ../../bin/apk/M5Apk.app/Contents/MacOS/M5Apk
# Generated by qmake (3.0) (Qt 5.6.1)
# Project:  M5Apk.pro
# Template: app
# Command: /Users/chenchaowei/Qt5.6.1/5.6/ios/bin/qmake -spec macx-ios-clang CONFIG+=release CONFIG+=iphoneos CONFIG+=device -spec macx-xcode -o M5Apk.xcodeproj/project.pbxproj M5Apk.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Users/chenchaowei/Qt5.6.1/5.6/ios/bin/qmake
M5Apk.xcodeproj/project.pbxproj: M5Apk.pro /Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/qmake.conf /Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/spec_pre.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/qdevice.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/device_config.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/unix.conf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/mac.conf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/ios.conf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/sanitize.conf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/gcc-base.conf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/gcc-base-mac.conf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/clang.conf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/clang-mac.conf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/ios/clang.conf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/ios/qmake.conf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/qconfig.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3drender.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_core.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_core_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_dbus.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_gui.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_help.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_help_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_location.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_location_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_network.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_network_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_nfc.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_opengl.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_positioning.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_qml.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_quick.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_script.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_script_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_sensors.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_sql.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_svg.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_testlib.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_uitools.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_websockets.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_webview.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_widgets.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_xml.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_gltfsceneparser.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qdds.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qicns.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qico.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qios.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtga.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtposition_geoclue.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/qt_functions.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/qt_config.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/features/qt_config.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/qmake.conf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-xcode/qmake.conf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/exclusive_builds.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/default_pre.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/mac/default_pre.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/features/default_pre.prf \
		global/Global.pri \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/resolve_config.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/features/resolve_config.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/default_post.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/mac/sdk.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/features/sdk.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/mac/default_post.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/mac/objective_c.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/warn_on.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/platforms/libqios.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/qt.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/features/qt.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/resources.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/moc.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/unix/opengl.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/uic.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/unix/thread.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/file_copies.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/mac/rez.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/testcase_targets.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/features/testcase_targets.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/exceptions.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/yacc.prf \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/lex.prf \
		M5Apk.pro \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/Default-568h@2x.png \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/LaunchScreen.xib \
		pic.qrc \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libQt5PlatformSupport.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libQt5DBus.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libqtfreetype.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libQt5Gui.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libqtharfbuzzng.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libQt5Core.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libqtpcre.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libQt5Widgets.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libQt5Sql.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libQt5Network.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/imageformats/libqdds.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/imageformats/libqicns.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/imageformats/libqico.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/imageformats/libqtga.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/imageformats/libqtiff.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/imageformats/libqwbmp.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/imageformats/libqwebp.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/sqldrivers/libqsqlite.prl \
		/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/bearer/libqgenericbearer.prl
	$(QMAKE) -spec macx-ios-clang CONFIG+=release CONFIG+=iphoneos CONFIG+=device -spec macx-xcode -o M5Apk.xcodeproj/project.pbxproj M5Apk.pro
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/spec_pre.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/qdevice.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/device_config.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/unix.conf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/mac.conf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/ios.conf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/sanitize.conf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/gcc-base.conf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/gcc-base-mac.conf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/clang.conf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/clang-mac.conf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/ios/clang.conf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/common/ios/qmake.conf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/qconfig.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dcore.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dinput.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dquick.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3drender.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_concurrent.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_core.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_core_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_dbus.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_gui.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_gui_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_help.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_help_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_labscontrols_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_labstemplates_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_location.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_location_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_multimedia.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_network.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_network_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_nfc.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_opengl.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_positioning.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_printsupport.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_qml.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_qml_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_qmltest.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_quick.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_quick_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_script.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_script_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_scripttools.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_sensors.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_sql.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_sql_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_svg.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_svg_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_testlib.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_uitools.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_webchannel.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_websockets.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_webview.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_webview_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_widgets.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_xml.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_xml_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_lib_zlib_private.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_gltfsceneparser.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qdds.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qicns.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qico.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qios.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qminimal.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qsvg.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtga.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtiff.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtposition_geoclue.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/modules/qt_plugin_qwebp.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/qt_functions.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/qt_config.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/features/qt_config.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/qmake.conf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-xcode/qmake.conf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/exclusive_builds.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/default_pre.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/mac/default_pre.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/features/default_pre.prf:
global/Global.pri:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/resolve_config.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/features/resolve_config.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/default_post.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/mac/sdk.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/features/sdk.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/mac/default_post.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/features/default_post.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/mac/objective_c.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/warn_on.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/platforms/libqios.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/qt.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/features/qt.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/resources.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/moc.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/unix/opengl.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/uic.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/unix/thread.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/file_copies.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/mac/rez.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/testcase_targets.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/features/testcase_targets.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/exceptions.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/yacc.prf:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/features/lex.prf:
M5Apk.pro:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/Default-568h@2x.png:
/Users/chenchaowei/Qt5.6.1/5.6/ios/mkspecs/macx-ios-clang/LaunchScreen.xib:
pic.qrc:
/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libQt5PlatformSupport.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libQt5DBus.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libqtfreetype.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libQt5Gui.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libqtharfbuzzng.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libQt5Core.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libqtpcre.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libQt5Widgets.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libQt5Sql.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/lib/libQt5Network.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/imageformats/libqdds.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/imageformats/libqicns.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/imageformats/libqico.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/imageformats/libqtga.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/imageformats/libqtiff.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/imageformats/libqwbmp.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/imageformats/libqwebp.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/sqldrivers/libqsqlite.prl:
/Users/chenchaowei/Qt5.6.1/5.6/ios/plugins/bearer/libqgenericbearer.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-ios-clang CONFIG+=release CONFIG+=iphoneos CONFIG+=device -spec macx-xcode -o M5Apk.xcodeproj/project.pbxproj M5Apk.pro

qmake_all: FORCE

